export default [
    {label: "Admiralty", value: "Admiralty"}, 
    {label: "Aljunied", value: "Aljunied"}, 
    {label: "Ang Mo Kio", value: "Ang Mo Kio"}, 
    {label: "Bartley", value: "Bartley"}, 
    {label: "Bayfront", value: "Bayfront"}, 
    {label: "Beauty World", value: "Beauty World"}, 
    {label: "Bedok", value: "Bedok"}, 
    {label: "Bedok North", value: "Bedok North"}, 
    {label: "Bedok Reservoir", value: "Bedok Reservoir"}, 
    {label: "Bencoolen", value: "Bencoolen"}, 
    {label: "Bendemeer", value: "Bendemeer"}, 
    {label: "Bishan", value: "Bishan"},
    {label: "Boon Keng", value: "Boon Keng"}, 
    {label: "Boon Lay", value: "Boon Lay"}, 
    {label: "Botanic Gardens", value: "Botanic Gardens"},
    {label: "Braddell", value: "Braddell"}, 
    {label: "Bras Basah", value: "Bras Basah"}, 
    {label: "Buangkok", value: "Buangkok"}, 
    {label: "Bugis", value: "Bugis"}, 
    {label: "Bukit Batok", value: "Bukit Batok"}, 
    {label: "Bukit Brown", value: "Bukit Brown"}, 
    {label: "Bukit Gombak", value: "Bukit Gombak"}, 
    {label: "Bukit Panjang", value: "Bukit Panjang"}, 
    {label: "Buona Vista", value: "Buona Vista"}, 
    {label: "Caldecott", value: "Caldecott"}, 
    {label: "Canberra", value: "Canberra"}, 
    {label: "Cashew", value: "Cashew"}, 
    {label: "Changi Airport", value: "Changi Airport"}, 
    {label: "Chinatown", value: "Chinatown"}, 
    {label: "Chinese Garden", value: "Chinese Garden"}, 
    {label: "Choa Chu Kang", value: "Choa Chu Kang"}, 
    {label: "City Hall", value: "City Hall"}, 
    {label: "Clarke Quay", value: "Clarke Quay"}, 
    {label: "Clementi", value: "Clementi"}, 
    {label: "Commonwealth", value: "Commonwealth"}, 
    {label: "Dakota", value: "Dakota"}, 
    {label: "Dhoby Ghaut", value: "Dhoby Ghaut"}, 
    {label: "Dover", value: "Dover"}, 
    {label: "Downtown", value: "Downtown"}, 
    {label: "Esplanade", value: "Esplanade"}, 
    {label: "Eunos", value: "Eunos"}, 
    {label: "Expo", value: "Expo"}, 
    {label: "Farrer Park", value: "Farrer Park"}, 
    {label: "Farrer Road", value: "Farrer Road"}, 
    {label: "Fort Canning", value: "Fort Canning"}, 
    {label: "Geylang Bahru", value: "Geylang Bahru"}, 
    {label: "Gul Circle", value: "Gul Circle"}, 
    {label: "HarbourFront", value: "HarbourFront"}, 
    {label: "Haw Par Villa", value: "Haw Par Villa"}, 
    {label: "Hillview", value: "Hillview"}, 
    {label: "Holland Village", value: "Holland Village"}, 
    {label: "Hougang", value: "Hougang"}, 
    {label: "Jalan Besar", value: "Jalan Besar"}, 
    {label: "Joo Koon", value: "Joo Koon"}, 
    {label: "Jurong East", value: "Jurong East"}, 
    {label: "Kaki Bukit", value: "Kaki Bukit"}, 
    {label: "Kallang", value: "Kallang"}, 
    {label: "Kembangan", value: "Kembangan"}, 
    {label: "Kent Ridge", value: "Kent Ridge"}, 
    {label: "Khatib", value: "Khatib"}, 
    {label: "King Albert Park", value: "King Albert Park"}, 
    {label: "Kovan", value: "Kovan"}, 
    {label: "Kranji", value: "Kranji"},
    {label: "Labrador Park", value: "Labrador Park"}, 
    {label: "Lakeside", value: "Lakeside"}, 
    {label: "Lavender", value: "Lavender"}, 
    {label: "Little India", value: "Little India"}, 
    {label: "Lorong Chuan", value: "Lorong Chuan"}, 
    {label: "MacPherson", value: "MacPherson"}, 
    {label: "Marina Bay", value: "Marina Bay"}, 
    {label: "Marina South Pier", value: "Marina South Pier"}, 
    {label: "Marsiling", value: "Marsiling"}, 
    {label: "Marymount", value: "Marymount"}, 
    {label: "Mattar", value: "Mattar"}, 
    {label: "Mountbatten", value: "Mountbatten"}, 
    {label: "Newton", value: "Newton"}, 
    {label: "Nicoll Highway", value: "Nicoll Highway"}, 
    {label: "Novena", value: "Novena"}, 
    {label: "One-north", value: "One-north"}, 
    {label: "Orchard", value: "Orchard"}, 
    {label: "Outram Park", value: "Outram Park"}, 
    {label: "Pasir Panjang", value: "Pasir Panjang"}, 
    {label: "Pasir Ris", value: "Pasir Ris"}, 
    {label: "Paya Lebar", value: "Paya Lebar"}, 
    {label: "Pioneer", value: "Pioneer"}, 
    {label: "Potong Pasir", value: "Potong Pasir"}, 
    {label: "Promenade", value: "Promenade"}, 
    {label: "Punggol", value: "Punggol"}, 
    {label: "Queenstown", value: "Queenstown"}, 
    {label: "Raffles Place", value: "Raffles Place"}, 
    {label: "Redhill", value: "Redhill"}, 
    {label: "Rochor", value: "Rochor"}, 
    {label: "Sembawang", value: "Sembawang"}, 
    {label: "Sengkang", value: "Sengkang"}, 
    {label: "Serangoon", value: "Serangoon"}, 
    {label: "Simei", value: "Simei"}, 
    {label: "Sixth Avenue", value: "Sixth Avenue"}, 
    {label: "Somerset", value: "Somerset"}, 
    {label: "Stadium", value: "Stadium"}, 
    {label: "Stevens", value: "Stevens"}, 
    {label: "Tai Seng", value: "Tai Seng"}, 
    {label: "Tampines", value: "Tampines"}, 
    {label: "Tampines East", value: "Tampines East"}, 
    {label: "Tampines West", value: "Tampines West"}, 
    {label: "Tan Kah Kee", value: "Tan Kah Kee"}, 
    {label: "Tanah Merah", value: "Tanah Merah"}, 
    {label: "Tanjong Pagar", value: "Tanjong Pagar"}, 
    {label: "Telok Ayer", value: "Telok Ayer"}, 
    {label: "Telok Blangah", value: "Telok Blangah"}, 
    {label: "Tiong Bahru", value: "Tiong Bahru"}, 
    {label: "Toa Payoh", value: "Toa Payoh"}, 
    {label: "Tuas Crescent", value: "Tuas Crescent"}, 
    {label: "Tuas Link", value: "Tuas Link"}, 
    {label: "Tuas West Road", value: "Tuas West Road"}, 
    {label: "Ubi", value: "Ubi"}, 
    {label: "Upper Changi", value: "Upper Changi"}, 
    {label: "Woodlands", value: "Woodlands"}, 
    {label: "Woodleigh", value: "Woodleigh"}, 
    {label: "Yew Tee", value: "Yew Tee"}, 
    {label: "Yio Chu Kang", value: "Yio Chu Kang"}, 
    {label: "Yishun", value: "Yishun"}];